### ISSUE TITLE
can I use srd-05vdc-sl-c model relay?

### ISSUE THREAD

**Issue by KushlaVR** [KushlaVR/WiFi-relay#1]
can I replace the relays you use with the srd-05vdc-sl-c model relay?

**Comment by KushlaVR** [comment]
You can use any relay you want.
For example thisi is comon wiring diagram for srd-05vdc-sl-c relay.

![3405972f2bf5464bb72de89564c7980b](https://user-images.githubusercontent.com/25207683/76429861-4ae6e680-63b8-11ea-9d8c-5e64f4daeec8.png)

Also you can attach transistor base to nay ESP pin. You just nead to adjust hardware.json file befor firmware upload.

**Comment by omerfarukaran** [comment]
Thank you very much for the information. But there is a situation like how we can place these relays on the PCB circuit. Do you have the opportunity to share the Proteus project?

**Comment by KushlaVR** [comment]
Have a loock to "schematic" folder.
There are 8 version of board (Proteus 8 projects files).
The latest one is assembled and shown on picture in homepage.
I can place this relay on schematic, but it will broke PCB layout. You musе redraw BCP by yourself.

**Comment by omerfarukaran** [comment]
yes, I tried very hard, but unfortunately pcb layout is disrupted. Therefore, I wanted to use 2 model relays instead of 3 units. Devices working with 220 Volts have high currents, even 10 amps will not be enough. I would appreciate it if you can recommend a 220v 10 amp or higher relay that you can recommend for this pcb design. If you can fix the PCB scheme according to the relay you will share, your right will not be paid.

**Comment by KushlaVR** [comment]
You can use Rev7 schematic and PCB for high current purpose.
It based on BTA16 triac (600V/16A).
PCB designed specially to place triacs on bottom layer. You can easly place heatsink on triacs.
Just keap in mind - the beggest curren => the beggest heatsink

Rev7 assembled on the right

![67151965_907317986294109_6893658514237947904_n](https://user-images.githubusercontent.com/25207683/76502819-6cde7880-644d-11ea-94d3-34f554fa46f5.jpg)

**Comment by omerfarukaran** [comment]
yes i saw revision 7, i also looked at other diagrams. I saw that at least the area takes up scheme 8. Space is very important in IoT projects. Still, thank you for all your support. Now I will try to do something different from the beginning.
